[package]
name = "gh-sizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.11", features = ["derive"] }
exitcode = "1.1.2"
tempfile = "3.4.0"

[dev-dependencies]
assert_cmd = "2.0.10"
insta = { version = "1.28.0", features = ["yaml"] }
mockall = "0.11.3"
predicates = "3.0.1"

[profile.dev.package.insta]
opt-level = 3

[features]
integration_tests = []