[package]
name = "gh-sizer"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.2", features = ["derive"] }
exitcode = "1.1.2"
tempfile = "3.5.0"

[dev-dependencies]
assert_cmd = "2.0.10"
insta = { version = "1.29.0", features = ["yaml"] }
mockall = "0.11.3"
predicates = "3.0.3"

[profile.dev.package.insta]
opt-level = 3

[features]
windows_integration_tests = []
linux_integration_tests = []