name: Run integration tests

on: push

jobs:
  run_integration_tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - name: Cache Rust dependencies
        uses: actions/cache@v3.3.1
        with:
          path: target
          key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
      - name: Install latest Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustc, cargo
          toolchain: nightly
          override: true
          target: ${{ matrix.job.target }}
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Install git-sizer
        uses: giantswarm/install-binary-action@v1.1.0
        with:
          binary: "git-sizer"
          version: "1.5.0"
          download_url: "https://github.com/github/${binary}/releases/download/v${version}/${binary}-${version}-linux-amd64.zip"
          tarball_binary_path: ${binary}
      - uses: valeriangalliat/action-sshd-cloudflared@v1
      - name: Run integration tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --ignored