name: Run integration tests (Windows)

on: push

jobs:
  run_integration_tests:
    name: Run integration tests
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache Rust dependencies
        uses: actions/cache@v4.2.2
        with:
          path: target
          key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
      - name: Install latest Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustc, cargo
          toolchain: nightly
          override: true
          target: ${{ matrix.job.target }}
      - name: Download zipped git-sizer release
        run: Invoke-WebRequest -Uri https://github.com/github/git-sizer/releases/download/v1.5.0/git-sizer-1.5.0-windows-amd64.zip -OutFile git-sizer-1.5.0-windows-amd64.zip
      - name: Create git-sizer directory to store binary
        run: New-Item -Name "git-sizer" -ItemType "directory"
      - name: Extract zipped git-sizer release
        run: Expand-Archive git-sizer-1.5.0-windows-amd64.zip -DestinationPath git-sizer
      - name: Make git-sizer available in $PATH
        run: |
          "D:\a\gh-sizer\gh-sizer\git-sizer" >> $env:GITHUB_PATH
      - name: Build with cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --features windows_integration_tests
      - name: Run integration tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features windows_integration_tests -- --show-output